/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maropu_lljvm_LLJVMNative */

#ifndef _Included_maropu_lljvm_LLJVMNative
#define _Included_maropu_lljvm_LLJVMNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     maropu_lljvm_LLJVMNative
 * Method:    parseBitcode
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_maropu_lljvm_LLJVMNative_parseBitcode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     maropu_lljvm_LLJVMNative
 * Method:    veryfyBitcode
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_maropu_lljvm_LLJVMNative_veryfyBitcode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     maropu_lljvm_LLJVMNative
 * Method:    asBitcode
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_maropu_lljvm_LLJVMNative_asBitcode
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
